jQuery(function($){'use strict';var $window=$(window);var $body=$('body');var $navWrap=$('.nav');var $navSubmenus=$navWrap.find('ul');var $mainNav=$('.navigation-main');var $mobileNav=$('#mobilemenu');$mainNav.each(function(){var $this=$(this);$this.clone().removeAttr('id').removeClass().appendTo($mobileNav.find('ul'));});$mobileNav.find('li').removeAttr('id');$mobileNav.mmenu({offCanvas:{position:'top',zposition:'front'},autoHeight:true,navbars:[{position:'top',content:['prev','title','close']}]});function setMenuClasses(){if(!$navWrap.is(':visible')){return;}
var windowWidth=$window.width();$navSubmenus.each(function(){var $this=$(this);var $parent=$this.parent();$parent.removeClass('nav-open-left');var leftOffset=$this.offset().left+$this.outerWidth();if(leftOffset>windowWidth){$parent.addClass('nav-open-left');}});}
setMenuClasses();var resizeTimer;$window.on('resize',function(){clearTimeout(resizeTimer);resizeTimer=setTimeout(function(){setMenuClasses();},350);});var offset=80;$('a[href*="#"]:not([href="#"])').not('.mobile-nav-trigger, .mm-btn, .mm-next').click(function(){var $this=$(this);if(location.pathname.replace(/^\//,'')==this.pathname.replace(/^\//,'')&&location.hostname==this.hostname&&!$this.parent().attr('role')==='tab'){var target=$(this.hash);target=target.length?target:$('[name='+this.hash.slice(1)+']');if(target.length){$('html,body').animate({scrollTop:target.offset().top-offset},400);return false;}}});if(window.location.hash.length){var target=$(window.location.hash);$('html,body').animate({scrollTop:target.offset().top-offset},400);}
$('.head-sticky').stick_in_parent({parent:'body',sticky_class:'is-stuck'});var $searchTrigger=$('.head-search-trigger');var $headSearchForm=$('.head-search-form');function dismissHeadSearch(e){if(e){e.preventDefault();}
$headSearchForm.removeClass('head-search-expanded');$body.focus();}
function displayHeadSearch(e){if(e){e.preventDefault();}
$headSearchForm.addClass('head-search-expanded').find('input').focus();}
function isHeadSearchVisible(){return $headSearchForm.hasClass('head-search-expanded')}
$searchTrigger.on('click',displayHeadSearch);$(document).on('keydown',function(e){e=e||window.e;if(e.keyCode===27&&isHeadSearchVisible()){dismissHeadSearch(e);}});$body.on('click',function(e){if(isHeadSearchVisible()){dismissHeadSearch();}}).find('.head-search-form, .head-search-trigger').on('click',function(e){e.stopPropagation();});$body.fitVids();var $itemEffectLists=$('.row-effect');if($itemEffectLists.length&&window.AnimOnScroll){$itemEffectLists.each(function(){var el=$(this).get(0);new AnimOnScroll(el,{minDuration:0.4,maxDuration:0.7,viewportFactor:0.2});});}
var $videoBg=$('.ci-video-background');function onYouTubeAPIReady($videoBg){if(typeof YT==='undefined'||typeof YT.Player==='undefined'){return setTimeout(onYouTubeAPIReady.bind(null,$videoBg),333);}
var $videoWrap=$videoBg.parents('.ci-video-wrap');var $video=$videoBg.find('div').get(0);var ytPlayer=new YT.Player($video,{videoId:$videoBg.data('video-id'),playerVars:{autoplay:1,controls:0,showinfo:0,modestbranding:1,loop:1,playlist:$videoBg.data('video-id'),fs:0,cc_load_policy:0,iv_load_policy:3,autohide:0},events:{onReady:function(event){event.target.mute();},onStateChange:function(event){if(event.data===YT.PlayerState.PLAYING){$videoWrap.addClass('visible');}}}});}
function onVimeoAPIReady($videoBg){if(typeof Vimeo==='undefined'||typeof Vimeo.Player==='undefined'){return setTimeout(onVimeoAPIReady.bind(null,$videoBg),333);}
var $videoWrap=$videoBg.parents('.ci-video-wrap');var player=new Vimeo.Player($videoBg,{id:$videoBg.data('video-id'),loop:true,autoplay:true,byline:false,title:false,autopause:false,});player.setVolume(0);player.addCuePoint(.1).catch(function(){$videoWrap.addClass('visible');});player.on('cuepoint',function(){$videoWrap.addClass('visible');});}
if($videoBg.length&&window.innerWidth>1080){$videoBg.each(function(){var $this=$(this);var firstScript=$('script');var videoType=$this.data('video-type');if(videoType==='youtube'){if(!$('#youtube-api-script').length){var tag=$('<script />',{id:'youtube-api-script'});tag.attr('src','https://www.youtube.com/player_api');firstScript.parent().prepend(tag);}
onYouTubeAPIReady($this);}else if(videoType==='vimeo'){if(!$('#vimeo-api-script').length){var tag=$('<script />',{id:'vimeo-api-script'});tag.attr('src','https://player.vimeo.com/api/player.js');firstScript.parent().prepend(tag);}
onVimeoAPIReady($this);}});}
var $cryptoTabular=$('.table-list-crypto');$cryptoTabular.each(function(){var $this=$(this);$this.dataTable({paging:false,info:false,searching:false,responsive:true,});});$window.on('load',function(){var $heroSlideshow=$('.page-hero-slideshow');var navigation=$heroSlideshow.data('navigation');var effect=$heroSlideshow.data('effect');var speed=$heroSlideshow.data('slide-speed');var auto=$heroSlideshow.data('autoslide');if($heroSlideshow.length){$heroSlideshow.slick({arrows:navigation==='arrows',dots:navigation==='dots',fade:effect==='fade',autoplaySpeed:speed,autoplay:auto===true,prevArrow:'<button type="button" class="slick-prev"><i class="fa fa-angle-left"></i></button>',nextArrow:'<button type="button" class="slick-next"><i class="fa fa-angle-right"></i></button>',rtl:$body.hasClass('rtl'),});}
var $grid=$('.row-isotope').isotope();var $filters=$('.item-filter');$filters.on('click',function(event){var $this=$(this);var filterValue=$this.data('filter');$filters.removeClass('filter-active');$this.addClass('filter-active');$($grid).removeClass(function(index,className){return(className.match(/(^|\s)row-effect*\S+/g)||[]).join(' ');});$grid.isotope({filter:filterValue});event.preventDefault();});});});